# Defination of static strings

login_email: "abc@gmail.com"
login_password: "1234"

your_Domain: "abcde.com"
your_SubDomain: "sub-domain"

format: "json"
lang: "en"
ipUrl: "http://members.3322.org/dyndns/getip"

